### ISSUE TITLE
command not found: gif

### ISSUE THREAD

**Issue by ianschwartz** [sgreben/yeetgif#1]
I tried installing it, both through the go get command as well as through the curl command. I'm on Mac OSX High Sierra.

After installing, I can't actually run gif because it always says command not found.

**Comment by sgreben** [comment]
Ah, you need to put it in your `PATH` also :)

E.g., for the `go get` way,

```sh
export PATH=$GOPATH/bin:$PATH
```

Or, otherwise
```sh
export PATH=<path-to-directory-containing-the-binary>:$PATH
```

to your .bashrc or .zshrc.

Alternatively, you can of course also run it with a full path, e.g. (if you put it in `~/Downloads`):

```sh
$ ~/Downloads/gif
```

**Comment by sgreben** [comment]
I'll add the above to the README in the today's release :)

**Comment by ianschwartz** [comment]
Yay thanks!

**Comment by sgreben** [comment]
You're welcome :)

**Comment by ianschwartz** [comment]
<img width="585" alt="screen shot 2018-10-19 at 3 48 32 pm" src="https://user-images.githubusercontent.com/13889001/47240506-7da0d100-d3b6-11e8-8f80-6751ed1b819d.png">
I added this, then closed and reopened terminal, and I still get 'command not found: gif'.

Sorry for bothering you with stupid questions

**Comment by ianschwartz** [comment]
![screen shot 2018-10-19 at 3 52 12 pm](https://user-images.githubusercontent.com/13889001/47240636-f6a02880-d3b6-11e8-96ee-878e9bf614a7.png)

**Comment by sgreben** [comment]
No worries, perhaps you don't have a `$GOPATH` :)

Could you try the other way? I.e. 

1) run the binary via with its full path
2) if that works, add the directory containing the binary to `$PATH`

So, e.g.:

```sh
mkdir /tmp/yeetgif-test
cd /tmp/yeetgif-test
curl -L https://github.com/sgreben/yeetgif/releases/download/1.15.0/gif_1.15.0_osx_x86_64.tar.gz | tar xz
./gif -h
export PATH=$PWD:$PATH
cd
gif -h
```

**Comment by sgreben** [comment]
Another thing - I erroneously had `-LO` (not `-L`) in the `curl | tar` command! So it didn't actually unpack anything :( I'll push it to master in a sec (almost done with a release..)

**Comment by sgreben** [comment]
Aaand one more question - what did `go get -u` return?

**Comment by sgreben** [comment]
@ianschwartz did this work? I would close the issue then :)

**Comment by sgreben** [comment]
@ianschwartz I'll close this now. Feel free to reopen if it's still unresolved :)
