### ISSUE TITLE
Need more information about how to use images/inputs

### ISSUE THREAD

**Issue by Swizzler121** [sgreben/yeetgif#5]
I've been staring at your readme and help documentation for going on an hour and cannot figure out for the life of me how your inputs work. I'm familiar with CLI programs but this reads like hieroglyphs to me. I'm using the windows version, but I'm not even sure it works on windows. Windows doesn't like <> in commands, and REALLY doesn't like arguments coming before the program execution. Could you provide an example of a line of code in command prompt or powershell?

Attached is the closest I was able to get a command to execute
![image](https://user-images.githubusercontent.com/36831696/113466800-236c1d00-9404-11eb-9f00-cbe7ee95045f.png)

If I add a > in front of the output, I get an empty output file, If I add a < in front of the input, powershell screams at me. If the <> are really supposed to be input and output, that's a bad idea, I'd use ffmpegs -i /-o
![image](https://user-images.githubusercontent.com/36831696/113466842-79d95b80-9404-11eb-80fd-0e32ce53e1d7.png)

**Comment by Swizzler121** [comment]
Update, I was able to get the second command working in command prompt, but might want to note that this program is completely incompatible with powershell, and also I'd reconsider your input/output flags, as they are super confusing as I kept reading it as some sort of nested command like `<xml>` or something.

**Comment by sgreben** [comment]
Those `<`,`>`,`|` are [POSIX shell constructs that redirect stdin/out](https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_07),  not `yeetgif` flags ;)

You can either...

- figure out [how to redirect i/o in PowerShell](https://stackoverflow.com/questions/11447598/redirecting-standard-input-output-in-windows-powershell), 
- or [install a POSIX-like shell on windows](https://superuser.com/questions/608106/how-can-i-use-a-bash-like-shell-on-windows) and then just use the same syntax as in the examples.

Cheers!
